version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: chasmx-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chasmx-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      # ✅ Use the service name "redis" for internal Docker DNS resolution
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app
      # Optional: helps prevent overwriting node_modules
      - /app/node_modules

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: chasmx-frontend
    ports:
      - "3000:3000"
    environment:
      # ✅ Use the backend's service name, not localhost
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./Client:/app
      - /app/node_modules
      - /app/.next

volumes:
  redis-data:
